---
# cPanel configuration to copy build folder to deployment location
deployment:
  tasks:
    - export DEPLOYPATH=/home/kitsgrow/piboy.ca/projects/fcc/fel/
    - /bin/cp fel/quote-machine/build $DEPLOYPATH
    - /bin/mv $DEPLOYPATH/build $DEPLOYPATH/quote-machine