---
# cPanel configuration to copy build folder to deployment location
deployment:
  tasks:
    - export DEPLOYPATH=/home/kitsgrow/piboy.ca/projects/fcc/fel/quote-machine
    - /bin/cp fel/quote-machine/build/* $DEPLOYPATH